TEMPLATEROOT = ../fall2017-lab

# compilation flags for gdb

CFLAGS  = -O1 -g
ASFLAGS = -g

# object files

OBJS=  $(STARTUP) main.o f3d_uart.o f3d_user_btn.o f3d_led.o newlib_stubs.o stm32f30x_rcc.o stm32f30x_gpio.o stm32f30x_usart.o

# include common make file

include $(TEMPLATEROOT)/c335.mk
